import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    > 
      <head>

  <meta
    name="shopify-api-key"
    content={
      process.env.SHOPIFY_CLIENT_ID || ''
    }
  />

  <script
    src="https://cdn.shopify.com/shopifycloud/app-bridge.js"
  />

</head>
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
