'use client';
import { useEffect,useState } from 'react';
export default function MetaEventsIntegrationManager(){
 const [state,setState]=useState<any>({connected:false,datasetId:''});const [datasetId,setDatasetId]=useState('');const [token,setToken]=useState('');const [busy,setBusy]=useState(false);
 async function load(){const r=await fetch('/api/integrations/meta-events',{cache:'no-store'});const j=await r.json();if(j?.ok){setState(j.data);setDatasetId(j.data.datasetId||'')}}
 useEffect(()=>{load()},[]);
 async function save(){if(!datasetId.trim()||!token.trim())return alert('Dataset / Pixel ID and access token are required');setBusy(true);const r=await fetch('/api/integrations/meta-events',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({datasetId,accessToken:token})});const j=await r.json();setBusy(false);if(!j?.ok)return alert(j?.error||'Unable to save Meta Events connection');setToken('');await load();}
 return <div className="space-y-3"><div className="rounded-lg border border-slate-200 bg-slate-50 p-3 text-[10px] leading-5 text-slate-600">This connection is for first-party event delivery through Meta Conversions API. It is separate from Meta Ads reporting and can be reused by Call Commerce and future lead modules.</div><label className="block text-[9px] font-semibold text-slate-500">Meta Dataset / Pixel ID<input value={datasetId} onChange={e=>setDatasetId(e.target.value)} className="mt-1 h-9 w-full rounded-lg border border-slate-200 px-2 text-[10px]"/></label><label className="block text-[9px] font-semibold text-slate-500">Conversions API access token<input type="password" value={token} onChange={e=>setToken(e.target.value)} placeholder={state.connected?'Enter a new token only to rotate it':'Access token'} className="mt-1 h-9 w-full rounded-lg border border-slate-200 px-2 text-[10px]"/></label><div className="flex items-center justify-between"><span className={`rounded-full px-2 py-1 text-[9px] font-semibold ${state.connected?'bg-emerald-50 text-emerald-700':'bg-slate-100 text-slate-600'}`}>{state.connected?'Connected':'Not connected'}</span><button disabled={busy} onClick={save} className="rounded-lg bg-slate-950 px-3 py-2 text-[9px] font-semibold text-white">{state.connected?'Update Connection':'Connect Meta Events'}</button></div></div>
}
